[package]
name = "fun-together-server"
version = "0.1.0"
edition = "2021"

[profile.release]
lto = true

[dependencies]
tungstenite = "0.17"

log = "0.4"
env_logger = "0.9"
once_cell = "1.16"

serde_cbor = "0.11"
serde = { version = "1", features = ["derive"] }
